[tool.poetry]
name = "generalized-rl"
version = "0.1.0"
description = ""
authors = ["7000015346 <DebaJyoti.Raychaudhuri@ap.sony.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
tensorflow = "1.15.0"
opencv-python = "^4.4.0.42"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
